---
title: "Comparison of variable importance"
author: "Marieke Vinkenoog"
date: "12/7/2021"
output: html_document
---

```{r}
library(readr)
library(dplyr)
library(tidyr)
library(ggplot2)
```


```{r setup, include=FALSE}
path <- 'C:/Users/mvink/OneDrive/PhD/Research/202105 SanguinStats Hb deferral/shap values comp/'

load_data <- function(path, filename) {
  data <- read.csv(paste0(path,filename), fileEncoding="UTF-8-BOM") %>%
    mutate(Id = replace(Id, grepl('﻿', Id, fixed = TRUE), 'rf-male')) %>%
    mutate(model = as.factor(Id),
           variable = as.factor(Variable)) %>%
    select(model, variable, attribution, value) %>%
    filter(!(variable %in% c('sex', 'year')))
  return(data)
}

get_mean_abs_attr <- function(data) {
  data <- data %>%
    group_by(model, variable) %>%
    summarise(mean_abs_attribution = mean(abs(attribution)))
  return(data)
}

scale_mean_abs_attr <- function(data) {
  data <- data %>%
    group_by(model) %>%
    arrange(desc(mean_abs_attribution), .by_group = TRUE) %>%
    mutate(scaled_mean_abs_attr = mean_abs_attribution / sum(mean_abs_attribution),
           rank = dense_rank(desc(mean_abs_attribution))) 
  return(data)
}

finland <- get_mean_abs_attr(load_data(path, 'finland.csv'))
netherlands <- get_mean_abs_attr(load_data(path, 'netherlands.csv'))

# No real data from BE and SA yet
belgium <- load_data(path, 'netherlands.csv') %>%
  mutate(attribution = attribution + rnorm(40000, 0, 0.5))
belgium <- get_mean_abs_attr(belgium)
southafrica <- load_data(path, 'finland.csv') %>%
  mutate(attribution = attribution + rnorm(40000, 0, 0.5))
southafrica <- get_mean_abs_attr(southafrica)

NL_s <- scale_mean_abs_attr(netherlands)
FL_s <- scale_mean_abs_attr(finland)
BE_s <- scale_mean_abs_attr(belgium)
SA_s <- scale_mean_abs_attr(southafrica)

```

Dataframes per model

```{r}
combine_per_model <- function(FL, NL, BE, SA, model) {
  df <- merge(FL[FL$model == model, ],
              NL[NL$model == model, ],
              by = 'variable',
              suffixes = c('.FL', '.NL')) %>%
    merge(BE[BE$model == model, ],
          by = 'variable') %>%
    rename(mean_abs_attribution.BE = mean_abs_attribution,
         scaled_mean_abs_attr.BE = scaled_mean_abs_attr,
         rank.BE = rank) %>%
    merge(SA[SA$model == model, ],
          by = 'variable') %>%
    rename(mean_abs_attribution.SA = mean_abs_attribution,
         scaled_mean_abs_attr.SA = scaled_mean_abs_attr,
         rank.SA = rank) %>%
    select(-c(model.FL, model.NL, model.x, model.y)) %>%
    rowwise() %>%
    mutate(avg_rank = mean(c(rank.FL, rank.NL, rank.BE, rank.SA)),
           avg_scaled_attr = mean(c(scaled_mean_abs_attr.FL,
                                    scaled_mean_abs_attr.NL,
                                    scaled_mean_abs_attr.BE,
                                    scaled_mean_abs_attr.SA))) %>%
    arrange(avg_rank) %>%
    pivot_longer(cols = -c(variable, avg_rank, avg_scaled_attr),
               names_to = c('.value', 'country'),
               names_sep = '\\.')
  return(df)
}

rf_male <- combine_per_model(FL_s, NL_s, BE_s, SA_s, model='rf-male')

rf_male %>% ggplot(aes(x = reorder(variable, desc(avg_rank)), y = scaled_mean_abs_attr, group = country)) +
  geom_line(aes(color = country), size = 2) +
  geom_col(aes(y = avg_scaled_attr), alpha = 0.1, position = 'identity') +
  coord_flip() + 
  xlab('Variable') + ylab('Scaled mean absolute attribution')


```
Only NL and FL

```{r}
combine_per_model <- function(FL, NL, model) {
  df <- merge(FL[FL$model == model, ],
              NL[NL$model == model, ],
              by = 'variable',
              suffixes = c('.FL', '.NL')) %>%
    select(-c(model.FL, model.NL)) %>%
    rowwise() %>%
    mutate(avg_rank = mean(c(rank.FL, rank.NL)),
           avg_scaled_attr = mean(c(scaled_mean_abs_attr.FL,
                                    scaled_mean_abs_attr.NL))) %>%
    arrange(avg_rank) %>%
    pivot_longer(cols = -c(variable, avg_rank, avg_scaled_attr),
               names_to = c('.value', 'country'),
               names_sep = '\\.')
  return(df)
}

plot_comp_model <- function(model_df, model) {
  plt <- model_df %>% ggplot(aes(x = reorder(variable, desc(avg_rank)), y = scaled_mean_abs_attr, group = country)) +
    geom_line(aes(color = country), size = 2) +
    geom_col(aes(y = avg_scaled_attr), alpha = 0.2, position = 'identity') +
    coord_flip() + 
    ggtitle(paste0('Variable importance, model ', model)) +
    xlab('Variable') + ylab('Scaled mean absolute attribution')
  return(plt)
}

for (model in unique(FL_s$model)) {
  df_model <- combine_per_model(FL_s, NL_s, model=model)
  print(plot_comp_model(df_model, model=model))
}

```















