---
title: "Analyze hyperparameters"
author: "Jarkko Toivonen"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(knitr)
```

## Hyperparameters


```{r}
base <- "/home/toivoja/FRCBS/Hb_predictor_container/results/jarkko-2022-01-29-svm-rf-10k-hyper/tmp"
svm_base <- base
rf_base <- "/home/toivoja/FRCBS/Hb_predictor_container/results/jarkko-2022-02-09-ranger-hyper"
#rf_base <- "/home/toivoja/FRCBS/Hb_predictor_container/results/jarkko-2022-02-04-ranger-hyper"
#rf_base <- "/home/toivoja/FRCBS/Hb_predictor_container/results/jarkko-2022-02-04-rf-hyper"

#rf_base <- "/home/toivoja/FRCBS/Hb_predictor_container/results/jarkko-2022-01-31-rf-hyper-new"
#svm_base <- "/home/toivoja/FRCBS/Hb_predictor_container/results/jarkko-2022-01-09-svm-hyper"
#rf_base <- "/home/toivoja/FRCBS/Hb_predictor_container/results/jarkko-2021-12-18-rf-hyper"

svm_male_hyper <- readRDS(sprintf("%s/svm-hyper-fit-male.rds", svm_base))
svm_female_hyper <- readRDS(sprintf("%s/svm-hyper-fit-female.rds", svm_base))

rf_male_hyper <- readRDS(sprintf("%s/rf-hyper-fit-male.rds", rf_base))
rf_female_hyper <- readRDS(sprintf("%s/rf-hyper-fit-female.rds", rf_base))
rf_model <- class(rf_male_hyper$finalModel)
```

```{r}
get_label <- function(hyper, name) {  # Get a pretty name for a hyperparameter
  hyper$modelInfo$parameters %>% filter(parameter==name) %>% pull(label)
}
```

## Support vector machine

```{r}
svm_male_hyper
svm_female_hyper
```

```{r}
df_svm_male <- as_tibble(svm_male_hyper$results)
df_svm_female <- as_tibble(svm_female_hyper$results)
svm_breaks <- unique(df_svm_male$C)
best_svm_male <- df_svm_male %>% inner_join(as_tibble(svm_male_hyper$bestTune))
best_svm_female <- df_svm_female %>% inner_join(as_tibble(svm_female_hyper$bestTune))
df_svm_male %>% ggplot(aes(x=C, y=ROC, color=as.factor(sigma))) + 
  geom_line() + 
  geom_point() + 
  scale_x_log10(breaks=svm_breaks) + 
  labs(title="Male", color="Sigma") + 
  geom_point(mapping=aes(x=C, ROC), data=best_svm_male, 
             color="black", fill=NA, size=5, shape=1)
df_svm_female %>% ggplot(aes(x=C, y=ROC, color=as.factor(sigma))) + 
  geom_line() + 
  geom_point() + 
  scale_x_log10(breaks=svm_breaks) + 
  labs(title="Female", color="Sigma") +
  geom_point(mapping=aes(x=C, ROC), data=best_svm_female, 
             color="black", fill=NA, size=5, shape=1)
```

## Random forest

```{r}
rf_male_hyper
rf_female_hyper
```

```{r}
df_rf_male <- as_tibble(rf_male_hyper$results)
df_rf_female <- as_tibble(rf_female_hyper$results)
mtry_label <- get_label(rf_male_hyper, "mtry")
nodesize_var <- if (rf_model == "ranger") "min.node.size" else "nodesize"
nodesize_label <- get_label(rf_male_hyper, nodesize_var)
#rf_breaks <- unique(df_rf_male$C)
best_rf_male <- df_rf_male %>% inner_join(as_tibble(rf_male_hyper$bestTune))
best_rf_female <- df_rf_female %>% inner_join(as_tibble(rf_female_hyper$bestTune))
gm <- df_rf_male %>% ggplot(aes(x=get(nodesize_var), y=ROC, color=as.factor(mtry))) + 
  geom_line() + 
  geom_point() + 
  #scale_x_log10()+#breaks=rf_breaks) + 
  labs(title="Male", x=nodesize_label, color=mtry_label) + 
  geom_point(mapping=aes(x=get(nodesize_var), ROC), data=best_rf_male, color="black", 
             fill=NA, size=5, shape=1) +
  theme(legend.position="bottom")
if (rf_model=="ranger")
  gm <- gm + facet_wrap(~splitrule)
gm
gf <- df_rf_female %>% ggplot(aes(x=get(nodesize_var), y=ROC, color=as.factor(mtry))) + 
  geom_line() + 
  geom_point() + 
  #scale_x_log10(breaks=rf_breaks) + 
  labs(title="Female", x=nodesize_label, color=mtry_label) +
  geom_point(mapping=aes(x=get(nodesize_var), ROC), data=best_rf_female, 
             color="black", fill=NA, size=5, shape=1) +
  theme(legend.position="bottom")
if (rf_model=="ranger")
  gf <- gf + facet_wrap(~splitrule)
gf
```

## Optimal hyperparameters

### Random forest

```{r}
kable(bind_rows(male=best_rf_male, female=best_rf_female, .id="sex") %>% 
        select(-c("ROCSD", "SensSD", SpecSD)), 
      digits=3)
```

### Support vector machine

```{r}
kable(bind_rows(male=best_svm_male, female=best_svm_female, .id="sex") %>% 
        select(-c("ROCSD", "SensSD", SpecSD)) %>%
        mutate(across(!sex, ~ formatC(., digit=3, format = "g"))))
      
      
#      format.args=list(digits=3, scientific=TRUE))
```


