---
title: "Comparison of scatter plots"
author: "Jarkko Toivonen"
date: "2023-04-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
results_base <- "../mariekes_datas/SanguinStats Hb deferral prediction/results/v0.32_results"
fi_dir <- file.path(results_base, "FL-10k-results-0.32")
be_dir <- file.path(results_base, "BE-10k-results-0.32")
```

## Scatter plots

```{r}
fi_predictions <- read_csv(file.path(fi_dir, "prediction.csv")) %>% filter(model %in% c("lmm", "dlmm"))
be_predictions <- read_csv(file.path(be_dir, "prediction.csv")) %>% filter(model %in% c("lmm", "dlmm"))
```

```{r}
generate_my_breaks <- function(step) {
  # Break between limits at every position that is multiple of 'step' 
  my_breaks <- function(limits) {
    #step <- 0.2
    m <- limits %/% step
    m <- ifelse(m < 0, m+1, m)
    m <- m*step
    return(seq(m[1], m[2], step))
  }
  return(my_breaks)
}
```

```{r}
df <- bind_rows(Finland=fi_predictions, Belgium=be_predictions, .id="country")
df <- df %>% mutate(model = factor(model, levels=c("lmm", "dlmm")))
helper <- function(df, sex) {
  df <- df %>% filter(sex == "male")
  threshold <- if_else(sex == "male", 135, 125)
  xymin <- min(min(df$predicted_value), min(df$original_value))
  xymax <- max(max(df$predicted_value), max(df$original_value))
  
  scatter_plot <- df %>% 
    ggplot(aes(x = original_value, y=predicted_value, color = factor(as.integer(original_label)))) +
    geom_point() +
    #xlim(xymin,xymax) + ylim(xymin,xymax) +
    scale_x_continuous(breaks = generate_my_breaks(20), limits=c(xymin,xymax)) +
    scale_y_continuous(breaks = generate_my_breaks(20), limits=c(xymin,xymax)) +
    geom_abline(intercept = 0, slope = 1) +
    labs(x = "Observed", y = "Predicted", colour = "Status") +
    scale_colour_discrete(labels=c("Accepted", "Deferred")) +
    geom_smooth(mapping=aes(x = original_value, y=predicted_value), colour="black", show.legend = FALSE) +
    geom_vline(xintercept = threshold, linetype = "dashed") +
    geom_hline(yintercept = threshold, linetype = "dashed") +
    theme(legend.position = "bottom") +
    facet_grid(country  ~ model) +
    labs(title=sprintf("Observed vs predicted Hb-values (%s)", sex))
}
male_scatter_plot <- helper(df, "male")
male_scatter_plot
female_scatter_plot <- helper(df, "female")
female_scatter_plot
ggsave("../results/male-scatter-plot-comparison.png", male_scatter_plot)
```

